### ISSUE TITLE
遗憾只能加速图片

### ISSUE THREAD

**Issue by xlsw** [mierhuo/Typecho-SimpleCDN#1]
WP有插件策略是替换静态资源（包括且不限于图片）的地址为七牛的镜像加速地址，且可以设置替换资源的文件类型（如：jpg、png、js等等）。如果typecho也支持这样做，烦请大大增加此功能

**Comment by Quarkay** [comment]
你好，感谢关注，应该是可以的。
但是目前在忙毕设，等过了这个口我会来进一步完善 :-)

**Comment by Quarkay** [comment]
你好，我最近抽时间读了Typecho源码，发现对于页面而言，插件无法改变最终全页面的结果，只能影响内容部分（标题，文章内容等）和一些页面基础设置。所以这个需求目前只能通过手动修改主题内容实现。
