### ISSUE TITLE
请教一下插件中这个函数replace_content(Widget_Archive $archive)

### ISSUE THREAD

**Issue by jozhn** [mierhuo/Typecho-SimpleCDN#2]
这个public static function replace_content(Widget_Archive $archive)函数是在什么时候执行的呢？
比如我想集成到主题中，除了把地址的参数写到themeCofig中，这个函数该怎么处理？
写到functions里的themeinit函数里还是单独写一个就行？

**Comment by jozhn** [comment]
谢谢我已经解决了。不过这个插件有一个bug是文章中即使是代码中的链接也会被替换，怎么解决呢？

**Comment by Quarkay** [comment]
你好，感谢关注，刚刚点错了ISSUE..不好意思

SimpleCDN之前的版本只是简单的替换，给自己用，所以有些情况并没有考虑。欢迎体验新版 :)
