### ISSUE TITLE
使用插件之后，第一篇文章在index中无法显示了

### ISSUE THREAD

**Issue by sailor103** [mierhuo/Typecho-SimpleCDN#3]
使用插件之后，第一篇文章在index中无法显示了，总是无法显示第一篇文章。请问如何解决。

**Comment by Quarkay** [comment]
重新测试了一下，开发版、正式版、老正式版均未复现这个问题。

当然，这个问题可以通过修改主题文件 index.php ，在其循环输出文章前加入 `<?php reset($this->stack) ?>`解决。

如果有其他朋友也出现了这个问题，请贴出来讨论一下。

此Issue先开着放着吧

**Comment by kbrx93** [comment]
也遇到了一样的问题，加入 `<?php reset($this->stack) ?>` 后解决。感谢！ @mierhuo
